[package]
name = "rustcraft"
version = "0.1.0"
authors = ["Rory N <rorynickolls@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
image = "*"
specs = { version = "0.16.1", features = [ "shred-derive", "parallel" ] }
uuid = { version = "0.8.2", features = [ "v4" ]}
cgmath = "0.18.0"
noise = "0.8.2"
rand = "0.8.5"

[profile.release-debug]
inherits = "release"
debug = true
