[package]
name = "cube-test"
version = "0.1.0"
authors = ["Rory N <rorynickolls@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
image = "*"
specs = { version = "0.16.1", features = [ "shred-derive" ] }
uuid = { version = "0.8.2", features = [ "v4" ]}